<?php

use Drupal\shopify\Entity\ShopifyProduct;

function shopify_product_load_by_product_id($product_id) {
  $query = \Drupal::entityQuery('shopify_product');
  $query->condition('product_id', $product_id);
  $ids = $query->execute();
  if ($ids) {
    $products = ShopifyProduct::loadMultiple($ids);
    return reset($products);
  }
}

function shopify_product_variant_load_by_variant_id($variant_id) {

}