shopify.settings:
  type: config_object
  label: 'Shopify settings'
  mapping:
    api:
      type: mapping
      label: 'API connection settings'
      mapping:
        domain:
          type: string
          label: 'Store domain'
        key:
          type: string
          label: 'API key'
        password:
          type: string
          label: 'Password'
        secret:
          type: string
          label: 'Shared secret'
        storefront_access_token:
          type: string
          label: 'Storefront Access Token'
    button:
      type: mapping
      label: 'Buy Button configuration'
      mapping:
        interface:
          type: mapping
          label: 'Buy Button interface'
          mapping:
            button_text:
              type: string
              label: 'Button text'
            show_price:
              type: boolean
              label: 'Show product variant price'
            show_title:
              type: boolean
              label: 'Show product variant title'
            show_image:
              type: boolean
              label: 'Show product variant image'
    cart:
      type: mapping
      label: 'Cart configuration'
      mapping:
        interface:
          type: mapping
          label: 'Shopify Cart Labeling Options'
          mapping:
            heading_label:
              type: string
              label: 'Cart heading'
            subtotal_label:
              type: string
              label: 'Subtotal label'
            show_order_note:
              type: boolean
              label: 'Provide order note'
            order_note_label:
              type: string
              label: 'Order note label'
            additional_info_text:
              type: string
              label: 'Additional information'
            checkout_button_label:
              type: string
              label: 'Checkout button label'
            empty_message:
              type: string
              label: 'Empty cart message'
    sync:
      type: mapping
      label: 'Data synchronization settings'
      mapping:
        html_import_format:
          type: string
          label: 'HTML import format'
        cron_sync_products:
          type: boolean
          label: 'Whether or not to import products during cron runs'
        cron_sync_collections:
          type: boolean
          label: 'Whether or not to import collections during cron runs'
        cron_sync_time:
          type: integer
          label: 'Duration (in seconds) between collection/products synchronization'

